version: '3.8'
services:
  app-consumer:
    build:
      context: .
    container_name: "consumer-service-app"
    networks:
      - back
    ports:
      - "8081:8081"
    environment:
      - SUPPLIER_URL=http://app-supplier:8080/api/v1
networks:
  back:
    driver: bridge